### ISSUE TITLE
suggestion to make a github actions ci.yml compatible with dsproject

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [pyscaffold/pyscaffoldext-dsproject#64]
# the problem

As noted by @maresb in this issue (https://github.com/pyscaffold/pyscaffoldext-markdown/issues/11),  both `pyscaffoldext-markdown` and `pyscaffoldext-dsproject` require git to be set up to run the tests.

Also related, this discussion on the pyscaffold repo: https://github.com/pyscaffold/pyscaffold/discussions/420

I wanted to have some CI to run on github actions for a custom pyscaffold extension that I am developing, so to not rely on the developer to run the tests locally.

## example

example of a `.github/workflows/ci.yml` file
(removed some redundant options for clarity and conciseness)
```yaml
name: tests

on:
  pull_request:  # Run in every PR

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      wheel-distribution: ${{ steps.wheel-distribution.outputs.path }}
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}  # deep clone for setuptools-scm
      - uses: actions/setup-python@v4
        id: setup-python
        with: {python-version: "3.11"}
      - name: Run static analysis and format checkers
        run: pipx run pre-commit run --all-files --show-diff-on-failure
      - name: Build package distribution files
        run: >-
          pipx run --python '${{ steps.setup-python.outputs.python-path }}'
          tox -e clean,build
      - name: Record the path of wheel distribution
        id: wheel-distribution
        run: echo "path=$(ls dist/*.whl)" >> $GITHUB_OUTPUT
      - name: Store the distribution files for use in other stages
        # `tests` and `publish` will use the same pre-built distributions,
        # so we make sure to release the exact same package that was tested
        uses: actions/upload-artifact@v3
        with:
          name: python-distribution-files
          path: dist/
          retention-days: 1

  test:
    needs: prepare
    strategy:
      matrix:
        python:
        - "3.7"  # oldest Python supported by PSF
        - "3.11"  # newest Python that is stable
        platform:
        - ubuntu-latest
        # - macos-latest
        # - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python }}
      - name: Retrieve pre-built distribution files
        uses: actions/download-artifact@v3
        with: {name: python-distribution-files, path: dist/}
      - name: Run tests
        run: >-
          pipx run --python '${{ steps.setup-python.outputs.python-path }}'
          tox --installpkg '${{ needs.prepare.outputs.wheel-distribution }}'
          -- -rFEx --durations 10 --color yes  # pytest args
```

Running this will trigger the `GitNotConfigured` error, see [pyscaffold/actions.py:222](https://github.com/pyscaffold/pyscaffold/blob/14ff8554f25c83845687315c0a251048e76784ba/src/pyscaffold/info.py#L129)

# a possible solution 

A possible solution is to run the `configure-git-credentials` github action with some dummy variables to **trick** the testing environment that git is set up.
https://github.com/marketplace/actions/configure-git-credentials

## example

```yaml
name: tests

on:
  pull_request:  # Run in every PR

concurrency:
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      wheel-distribution: ${{ steps.wheel-distribution.outputs.path }}
    steps:
      - uses: actions/checkout@v3
        with: {fetch-depth: 0}  # deep clone for setuptools-scm
      - uses: actions/setup-python@v4
        id: setup-python
        with: {python-version: "3.11"}
      - name: Run static analysis and format checkers
        run: pipx run pre-commit run --all-files --show-diff-on-failure
      - name: Build package distribution files
        run: >-
          pipx run --python '${{ steps.setup-python.outputs.python-path }}'
          tox -e clean,build
      - name: Record the path of wheel distribution
        id: wheel-distribution
        run: echo "path=$(ls dist/*.whl)" >> $GITHUB_OUTPUT
      - name: Store the distribution files for use in other stages
        # `tests` and `publish` will use the same pre-built distributions,
        # so we make sure to release the exact same package that was tested
        uses: actions/upload-artifact@v3
        with:
          name: python-distribution-files
          path: dist/
          retention-days: 1

  test:
    needs: prepare
    strategy:
      matrix:
        python:
        - "3.7"  # oldest Python supported by PSF
        - "3.11"  # newest Python that is stable
        platform:
        - ubuntu-latest
        # - macos-latest
        # - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python }}
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          name: 'Derp McDerpface'
          email: 'derp@mcderp.face'
          actor: 'DerpMcDerpface'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Retrieve pre-built distribution files
        uses: actions/download-artifact@v3
        with: {name: python-distribution-files, path: dist/}
      - name: Run tests
        run: >-
          pipx run --python '${{ steps.setup-python.outputs.python-path }}'
          tox --installpkg '${{ needs.prepare.outputs.wheel-distribution }}'
          -- -rFEx --durations 10 --color yes  # pytest args
```

# conclusion

This `ci.yml` configuration allows for an automated run of the tests in CI.
If this seems like a good option for improvement, I'll make a PR with the suggested changes
